### PR TITLE
Clean up cabal file

### PR DESCRIPTION
**Pull request by Toxaris**
This adresses issue #6.

Two open questions:
- is test coverage checking still working? (see 434eeffec633a270978ed71093986e3b9f0fc36f)
- what should happen with `tests/TestMain.hs`? (see 3d43e805e13eecbf8647664558e74b081d713dae)

### CODE REVIEW

**Comment by Toxaris** [comment]
@tewe, what do you think about this?

**Comment by Toxaris** [comment]
Should I rebase this on top of current master?

**Comment by Toxaris** [comment]
Any thoughts about this, @tewe?

**Comment by tewe** [comment]
I won't be able to test this until Sunday, but it looks good.

Why not always work with all warnings?

**Comment by Toxaris** [comment]
The setting for warnings was different for the test-suite and the library before my changes, so I wanted to keep that difference.

(For an eventual Hackage release, it would be good if `cabal install uroboro` by users would not show any warnings, I think).

**Comment by Toxaris** [comment]
Should I rebase this so it can be merged?

**Comment by Toxaris** [comment]
Rebased and ready to merge.

**Pull request merged**
